language: go

script: env GOOS=linux GOARCH=amd64 go build -v application.go && mv application dota2-replay-chat-linux-amd64

env:
  GITHUB_TOKEN=$GITHUB_TOKEN

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "./dota2-replay-chat-linux-amd64"
  skip_cleanup: true
  on:
    tags: true
