#! /bin/bash
env GOOS=linux GOARCH=amd64 go build -v application.go
mv application dota2-replay-chat-linux-amd64

env GOOS=darwin GOARCH=amd64 go build -v application.go
mv application dota2-replay-chat-darwin-amd64
